services:
  # Flask Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document_retrieval_app
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
      - redis
    environment:
      - FLASK_ENV=development

  # Elasticsearch for Document Storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # Redis for Caching and Rate Limiting
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  es_data:
    driver: local
